"""
Vision Engine Interface.

Owned by: Developer 4 (Multimodal Engineer)
Subsystem: multimodal
"""

from typing import Optional

from workbench.core.types import Evidence, ResourceReference
from workbench.multimodal.mapping import outcome_to_evidence
from workbench.multimodal.pipeline.internal_model import ExtractionOutcome
from workbench.multimodal.pipeline.vision_extraction import (
    DEFAULT_MAX_RETRIES,
    DEFAULT_MAX_VISION_PAGES,
    DEFAULT_VISION_DPI,
    VisionExtractionPipeline,
)
from workbench.multimodal.ports.artifact_store import ArtifactStore
from workbench.multimodal.ports.resource_resolver import ResourceResolver
from workbench.multimodal.ports.vision_model import VisionModelClient


class VisionEngine:
    """
    Interface for visual comprehension models.
    """

    def analyze_image(self, resource: ResourceReference, prompt: str) -> list[Evidence]:
        """
        Analyzes visual features, diagrams, and technical drawings.
        """
        raise NotImplementedError("VisionEngine.analyze_image will be implemented by Developer 4.")


class LocalVisionEngine(VisionEngine):
    """Vision engine over the injected VisionModelClient port.

    Model-agnostic: which model answers is decided by whatever client is
    injected (eventually a Model Registry adapter). This class never names a
    model.

    Evidence from this engine always carries ConfidenceSource.VISION_MODEL.
    That value is generated by the model, not measured, and must never be
    compared with or averaged against OCR_ENGINE confidence.
    """

    def __init__(
        self,
        client: VisionModelClient,
        resolver: ResourceResolver,
        artifact_store: ArtifactStore,
        dpi: int = DEFAULT_VISION_DPI,
        max_pages: int = DEFAULT_MAX_VISION_PAGES,
        max_retries: int = DEFAULT_MAX_RETRIES,
        accept_model_confidence: bool = True,
    ) -> None:
        self._pipeline = VisionExtractionPipeline(
            client=client,
            resolver=resolver,
            artifact_store=artifact_store,
            dpi=dpi,
            max_pages=max_pages,
            max_retries=max_retries,
            accept_model_confidence=accept_model_confidence,
        )

    def analyze_image(self, resource: ResourceReference, prompt: str) -> list[Evidence]:
        """Contract method: evidence only. See MultimodalProcessor.process
        for the full result including Artifact records."""
        return outcome_to_evidence(self._pipeline.run(resource, prompt))

    def analyze(self, resource: ResourceReference, objective: str) -> ExtractionOutcome:
        """Internal richer form used by MultimodalProcessor."""
        return self._pipeline.run(resource, objective)
